const topTrendingBooks = [
  {
    id: 1,
    title: "Killer Peter",
    number: "#K035",
    price: "₹250",
    nft: 200,
    studio: "South",
    nftLeft: 35,
    ongoing: "close",
    remainingNft: "Remaining NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/killer_peter.jpg",
    royalty: "0.4% Royalty Share + Reward Coins",
    movieDate: "08/03/2025",
    movieDuration: "1H:15M:25S",
    timeValid: "Valid Till",
  },
  {
    id: 2,
    title: "Shadow Hunter",
    number: "#K102",
    price: "₹300",
    nft: 180,
    studio: "Bollywood",
    nftLeft: 40,
    ongoing: "open",
    remainingNft: "Available NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/shadow_hunter.jpg",
    royalty: "0.5% Royalty Share + Special Rewards",
    movieDate: "15/06/2025",
    movieDuration: "2H:05M:10S",
    timeValid: "Expires Soon",
  },
  {
    id: 1,
    title: "Killer Peter",
    number: "#K035",
    price: "₹250",
    nft: 200,
    studio: "South",
    nftLeft: 35,
    ongoing: "close",
    remainingNft: "Remaining NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/killer_peter.jpg",
    royalty: "0.4% Royalty Share + Reward Coins",
    movieDate: "08/03/2025",
    movieDuration: "1H:15M:25S",
    timeValid: "Valid Till",
  },
  {
    id: 2,
    title: "Shadow Hunter",
    number: "#K102",
    price: "₹300",
    nft: 180,
    studio: "Bollywood",
    nftLeft: 40,
    ongoing: "open",
    remainingNft: "Available NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/shadow_hunter.jpg",
    royalty: "0.5% Royalty Share + Special Rewards",
    movieDate: "15/06/2025",
    movieDuration: "2H:05M:10S",
    timeValid: "Expires Soon",
  },
  {
    id: 1,
    title: "Killer Peter",
    number: "#K035",
    price: "₹250",
    nft: 200,
    studio: "South",
    nftLeft: 35,
    ongoing: "close",
    remainingNft: "Remaining NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/killer_peter.jpg",
    royalty: "0.4% Royalty Share + Reward Coins",
    movieDate: "08/03/2025",
    movieDuration: "1H:15M:25S",
    timeValid: "Valid Till",
  },
  {
    id: 2,
    title: "Shadow Hunter",
    number: "#K102",
    price: "₹300",
    nft: 180,
    studio: "Bollywood",
    nftLeft: 40,
    ongoing: "open",
    remainingNft: "Available NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/shadow_hunter.jpg",
    royalty: "0.5% Royalty Share + Special Rewards",
    movieDate: "15/06/2025",
    movieDuration: "2H:05M:10S",
    timeValid: "Expires Soon",
  },
  {
    id: 1,
    title: "Killer Peter",
    number: "#K035",
    price: "₹250",
    nft: 200,
    studio: "South",
    nftLeft: 35,
    ongoing: "close",
    remainingNft: "Remaining NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/killer_peter.jpg",
    royalty: "0.4% Royalty Share + Reward Coins",
    movieDate: "08/03/2025",
    movieDuration: "1H:15M:25S",
    timeValid: "Valid Till",
  },
  {
    id: 2,
    title: "Shadow ",
    number: "#K102",
    price: "₹300",
    nft: 180,
    studio: "Bollywood",
    nftLeft: 40,
    ongoing: "open",
    remainingNft: "Available NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/shadow_hunter.jpg",
    royalty: "0.5% Royalty Share + Special Rewards",
    movieDate: "15/06/2025",
    movieDuration: "2H:05M:10S",
    timeValid: "Expires Soon",
  },
];

const popularTodayBooks = [
  {
    id: 3,
    title: "Lost Empire",
    number: "#P078",
    price: "₹350",
    nft: 150,
    studio: "Hollywood",
    nftLeft: 25,
    ongoing: "open",
    remainingNft: "Available NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/lost_empire.jpg",
    royalty: "0.6% Royalty Share + VIP Pass",
    movieDate: "20/09/2025",
    movieDuration: "2H:20M:15S",
    timeValid: "Limited Time",
  },
  {
    id: 4,
    title: "Echoes of Time",
    number: "#P056",
    price: "₹320",
    nft: 175,
    studio: "Hollywood",
    nftLeft: 30,
    ongoing: "close",
    remainingNft: "Remaining NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/echoes_of_time.jpg",
    royalty: "0.3% Royalty Share + Signed Posters",
    movieDate: "05/12/2025",
    movieDuration: "1H:50M:30S",
    timeValid: "Valid Till",
  },
  {
    id: 3,
    title: "Lost Empire",
    number: "#P078",
    price: "₹350",
    nft: 150,
    studio: "Hollywood",
    nftLeft: 25,
    ongoing: "open",
    remainingNft: "Available NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/lost_empire.jpg",
    royalty: "0.6% Royalty Share + VIP Pass",
    movieDate: "20/09/2025",
    movieDuration: "2H:20M:15S",
    timeValid: "Limited Time",
  },
  {
    id: 4,
    title: "Echoes of Time",
    number: "#P056",
    price: "₹320",
    nft: 175,
    studio: "Hollywood",
    nftLeft: 30,
    ongoing: "close",
    remainingNft: "Remaining NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/echoes_of_time.jpg",
    royalty: "0.3% Royalty Share + Signed Posters",
    movieDate: "05/12/2025",
    movieDuration: "1H:50M:30S",
    timeValid: "Valid Till",
  },
];

const newlyLaunchedBooks = [
  {
    id: 5,
    title: "Neon City",
    number: "#N201",
    price: "₹400",
    nft: 220,
    studio: "Sci-Fi Studio",
    nftLeft: 45,
    ongoing: "open",
    remainingNft: "Available NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/neon_city.jpg",
    royalty: "0.7% Royalty Share + Exclusive Merchandise",
    movieDate: "01/11/2025",
    movieDuration: "2H:30M:10S",
    timeValid: "Expires Soon",
  },
  {
    id: 6,
    title: "Cybernetica",
    number: "#N220",
    price: "₹410",
    nft: 190,
    studio: "Futuristic Films",
    nftLeft: 55,
    ongoing: "open",
    remainingNft: "Available NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/cybernetica.jpg",
    royalty: "0.8% Royalty Share + Special Access",
    movieDate: "18/01/2026",
    movieDuration: "2H:40M:20S",
    timeValid: "Limited Time",
  },
  {
    id: 5,
    title: "Neon City",
    number: "#N201",
    price: "₹400",
    nft: 220,
    studio: "Sci-Fi Studio",
    nftLeft: 45,
    ongoing: "open",
    remainingNft: "Available NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/neon_city.jpg",
    royalty: "0.7% Royalty Share + Exclusive Merchandise",
    movieDate: "01/11/2025",
    movieDuration: "2H:30M:10S",
    timeValid: "Expires Soon",
  },
  {
    id: 6,
    title: "Cybernetica",
    number: "#N220",
    price: "₹410",
    nft: 190,
    studio: "Futuristic Films",
    nftLeft: 55,
    ongoing: "open",
    remainingNft: "Available NFTs",
    nftRemaining: "NFT's Remaining",
    image: "/images/cybernetica.jpg",
    royalty: "0.8% Royalty Share + Special Access",
    movieDate: "18/01/2026",
    movieDuration: "2H:40M:20S",
    timeValid: "Limited Time",
  },
];

export { topTrendingBooks, popularTodayBooks, newlyLaunchedBooks };
